standalone_tags:
  [
    {id: 1, size: 0.05, name: map},
    {id: 22, size: 0.05, name: map},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'map',
      layout:
        [
          {id: 1, size: 0.05, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 22, size: 0.05, x: 0.0000, y: 0.0000, z: 0.0000, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
        ]
    },
  ]
